version: '3.3'

services:
  whalesay:
    image: nikovirtala/whalesay:${TAG:-latest}
    ports:
      - 80:80
    networks:
      - whalesay
    deploy:
      mode: global
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  whalesay:
    driver: overlay
    driver_opts:
      encrypted: "true"
    external: false

