version: '3.6'

services:
  whalesay:
    image: nikovirtala/whalesay:latest
    ports:
      - 8080:8080
    networks:
      - whalesay
    deploy:
      mode: replicated
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: always

networks:
  whalesay:
    driver: overlay
    driver_opts:
      encrypted: "true"
    external: false

