apiVersion: apps/v1
kind: Deployment
metadata:
  name: whalesay
  labels:
    app: whalesay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whalesay
  template:
    metadata:
      labels:
        app: whalesay
    spec:
      containers:
      - name: whalesay
        image: nikovirtala/whalesay:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: whalesay
  labels:
    app: whalesay
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: whalesay

