name: On Push to Master - Build and Push to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./image
          file: ./image/Dockerfile
          push: true
          tags: nikovirtala/whalesay:latest